<joi> ::= <component>                       # Zuweisung
<component> ::= 'component' <componentName> # Seqzenz
<interfaces> ::= {<componentInterface>}     # Optionale Wiederholung
<type> ::= ('component' | 'interface')      # Alternative
<componentName> ::= String                  # Terminale
